import os
import uvicorn
import json
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from dotenv import load_dotenv
import google.generativeai as genai

# Load environment variables from .env file
load_dotenv()

# Configure the Gemini API
api_key = os.getenv("GOOGLE_API_KEY")
if not api_key:
    raise RuntimeError("GOOGLE_API_KEY not found in .env file")
genai.configure(api_key=api_key)

app = FastAPI()

# Pydantic model for request body
class Prompt(BaseModel):
    prompt: str

class Authority(BaseModel):
    id: int
    name: str

class RecommendationRequest(BaseModel):
    category: str
    description: str
    latitude: float
    longitude: float
    authorities: list[Authority]

class GenerateComplaintTextRequest(BaseModel):
    category: str
    confidence: float
    latitude: float
    longitude: float

@app.post("/generate")
async def generate_text(request: Prompt):
    """
    Receives a prompt and returns text generated by the Gemini model.
    """
    try:
        model = genai.GenerativeModel('gemini-2.5-flash')
        response = model.generate_content(request.prompt)
        return {"text": response.text}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/generate_complaint_text")
async def generate_complaint_text(request: GenerateComplaintTextRequest):
    """
    Generates an appropriate title and description for a complaint
    based on the detected category, confidence, and location using the Gemini model.
    """
    prompt = (
        f"You are an AI assistant specialized in generating civic complaint details for Dhaka city.\n\n"
        f"Generate a concise title (max 10 words) and a brief description (max 30 words) for a complaint based on the following details:\n\n"
        f"Detected Category: {request.category}\n"
        f"AI Confidence: {request.confidence}%\n"
        f"Location (Latitude, Longitude): ({request.latitude}, {request.longitude})\n\n"
        f"Rules:\n"
        f"- The title should be engaging and informative for the general public, try adding location detail such as 'seen on XYZ sidewalk'.\n"
        f"- The description should be worded simply and colloquially and should summarize the issue, its severity and hazards.\n"
        f"- If the detected category is generic or ambiguous, prioritize a more general description.\n"
        f"- Return ONLY valid JSON.\n\n"
        f"Output format:\n"
        f"{{\n"
        f"  \"title\": \"string\",\n"
        f"  \"description\": \"string\"\n"
        f"}}"
    )
    try:
        model = genai.GenerativeModel('gemini-2.5-flash')
        print("-----GENERATE COMPLAINT TEXT PROMPT-----")
        print(prompt)
        response = model.generate_content(prompt)
        print("-----GENERATE COMPLAINT TEXT RESPONSE-----")
        print(response.text)
        # Extract JSON from markdown code block if present
        json_string = response.text.strip()
        if json_string.startswith("```json") and json_string.endswith("```"):
            json_string = json_string[len("```json"): -len("```")].strip()
        return json.loads(json_string)
    except Exception as e:
        print("-----GENERATE COMPLAINT TEXT ERROR-----")
        print(str(e))
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/recommend-authority")
async def recommend_authority(request: RecommendationRequest):
    """
    Receives complaint details and a list of authorities,
    and returns a recommended authority from the Gemini model.
    """
    authorities_list_str = "\n".join([f"{a.id}. {a.name}" for a in request.authorities])
    prompt = (
        f"You are an AI civic issue routing assistant for Dhaka city.\n\n"
        f"Select the most appropriate authority from the list below, based on complaint location and issue category.\n"
        f"Return ONLY valid JSON.\n\n"
        f"Authorities:\n"
        f"{authorities_list_str}\n\n"
        f"Complaint Details:\n"
        f"Category: {request.category}\n"
        f"Description: {request.description}\n"
        f"Latitude: {request.latitude}\n"
        f"Longitude: {request.longitude}\n\n"
        f"Rules:\n"
        f"- Choose exactly one authority\n"
        f"- Do NOT invent authorities\n"
        f"- Include a confidence score between 0 and 1\n"
        f"- JSON ONLY (no markdown, no text)\n\n"
        f"Output format:\n"
        f"{{\n"
        f"  \"authorityCompanyId\": number,\n"
        f"  \"confidence\": number,\n"
        f"  \"reason\": string\n"
        f"}}"
    )
    try:
        model = genai.GenerativeModel('gemini-2.5-flash')
        print("-----PROMPT-----")
        print(prompt)
        response = model.generate_content(prompt)
        print("-----RESPONSE-----")
        print(response.text)
        # Assuming the model returns a raw JSON string.
        # More robust parsing might be needed in a real application.
        return json.loads(response.text)
    except Exception as e:
        print("-----ERROR-----")
        print(str(e))
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8001)
